version: "3"

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts: 
                      device: /home/bhielsch/data/wordpress
                      o: bind
        
        mariadb:
                name: mariadb
                driver: local
                driver_opts: 
                        device: /home/bhielsch/data/mysql
                        o: bind

networks:
  inception: 
      name: inception
      driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
    	-mariadb:/var/lib/mysql
    env_file:
    	- .env
    	networks:
    	  - inception
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on: 
      -mariadb
    volumes: 
      -wordpress:/var/www/html
    env_file:
      -.env
    networks: 
      -inception
    restart: always
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    volumes:
      -wordpress:/var/www/html
    networks:
      - inception
    restart: always
